### ISSUE TITLE
三星note10+（SM-N976N）构建失败

### ISSUE THREAD

**Issue by Star-Seven** [DogDayAndroid/Android-Kernel-Builder#1]
请帮忙看看，如何直接在源码中植入kernelsu构建？（我原来fork的源码可以构建内核，如果直接修改能合并构建那可能会更好？）
或者，如何使用此此仓库配置构建适合的内核？谢谢！

源码地址:https://github.com/Star-Seven/samsung-exynos9820  分支devel

![QQ图片20230610144549](https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/72426083/0cd705c7-7385-4aa0-8195-204bd2daac04)

**Comment by easterNday** [comment]
请附上原来的编译命令以及使用的编译工具链链接。
目前就截图来看问题是编译工具链出现了问题。

**Comment by Star-Seven** [comment]
原源码中是直接内置了编译工具链（https://github.com/CruelKernel/samsung-exynos9820-toolchain）
![工具链](https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/72426083/21c898cd-1714-4a75-8222-c148a1745b4a)
![QQ截图20230610145814](https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/72426083/23b64966-62ed-455f-958d-25ead337fbb6)

**Comment by Star-Seven** [comment]
非常感谢！

**Comment by easterNday** [comment]
下午尝试了一下使用他的编译工具链，仍然会出现`-Werror`错误，暂时不清楚原因，初步判断是编译工具链问题（？）。

或者您可以尝试手动修复报错，例如报错如下：

```
 /home/runner/work/Thyme-Kernel-Builder/Thyme-Kernel-Builder/SM-N976N_exynos9820-d2xks/SM-N976N/arch/arm64/mm/fault.c:294:14: error: variable 'msg' set but not used [-Werror,-Wunused-but-set-variable]
        const char *msg;
                    ^
1 error generated.
```

报错信息显示`-Wunused-but-set-variable]`，因此您可以考虑修改`Makefile`文件，注释其中的如下行[KBUILD_CFLAGS += $(call cc-disable-warning, unused-but-set-variable)](https://github.com/Star-Seven/samsung-exynos9820/blob/e602e1bcaec4fe28ede4fc89b348462e11044086/Makefile#L847)，以此类推。

此方法目前只针对`-Werror`报错。

**Comment by Star-Seven** [comment]
好的，谢谢，晚点我试试

**Comment by easterNday** [comment]
如果您只是想在内核中使用 `KernelSU` 的话，我可以给您提供一些解决方案。

- 官方文档：[如何为非 GKI 内核集成 KernelSU](https://kernelsu.org/zh_CN/guide/how-to-integrate-for-non-gki.html#introduction)

你可以将仓库克隆到本地后执行相关指令随后推送并检查编译结果。

如果想使用本仓库进行编译，似乎还存在部分问题，目前看起来是部分 `-Werror` 问题，其他原因暂时还不清楚，可能是由于提供的仓库中编译脚本中做了部分其他修改导致的，因此可以使用上面的方法先在本地仓库进行调试。

**Comment by Star-Seven** [comment]
只能参照官方文档进行本地编译试试了。直接在github仓库编译确实走不下去。再次感谢！

**Comment by easterNday** [comment]
请参考我的[复刻提交](https://github.com/easterNday/samsung-exynos9820/commit/54edd3883aade78d806a48e50b61c0560499f540)。

在这段代码里，我实现了简单的KIernelSU的同步，同时我移除了`Magisk`，如果您需要同时开启`Magisk`，请恢复[对应行](https://github.com/easterNday/samsung-exynos9820/commit/54edd3883aade78d806a48e50b61c0560499f540#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L60)。

这只是一个简单实现，原项目代码中存在很多其他功能，因此请确保不会冲突。

**Comment by Star-Seven** [comment]
已成功构建，现在就是提示内核不支持overlayfs，模块功能无法运作。

**Comment by easterNday** [comment]
首先尝试将 `Magisk` 的编译配置选项进行恢复，编译后测试是否可以使用 `KernelSU`，这是因为似乎 `Magisk` 也启用了 `overlayfs`。

如果带 `Magisk` 版本的 `KernelSU` 内核可以正常使用 `KernelSU`，则可以移步[kernel/configs/cruel](https://github.com/Star-Seven/samsung-exynos9820/blob/Star-Seven-kernelsu/kernel/configs/cruel%2Bmagisk.conf#L1-L14)，将其中的配置全部复制到你的 `defconfig` 中后关闭 `Magisk` 的编译配置选项后进行编译应该就可以了。

当然这其中似乎有部分关于 `Magisk` 的配置，可以自行斟酌删除。

**Comment by Star-Seven** [comment]
原内核（magisk版）的kernelsu是不可用的。编译后的kernelsu内核magisk也还能正常用（可能这就是问题？）尝试按kernelsu提交的issue（https://github.com/tiann/KernelSU/issues/263）关闭了也还是不行，可能需要重新修改magisk配置以关闭magisk才行
[KernelSU_bugreport_2023-06-13_07_55.tar.gz](https://github.com/DogDayAndroid/Android-Kernel-Builder/files/11729210/KernelSU_bugreport_2023-06-13_07_55.tar.gz)
![Sevenstar_20230613_081532](https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/72426083/5a22cbaa-6d6d-4d51-918d-261358ebd25f)

**Comment by easterNday** [comment]
> 原内核（magisk版）的kernelsu是不可用的。编译后的kernelsu内核magisk也还能正常用（可能这就是问题？）尝试按kernelsu提交的issue  https://github.com/tiann/KernelSU/issues/263
> 关闭了也还是不行，可能需要重新修改magisk配置以关闭magisk才行
> [KernelSU_bugreport_2023-06-13_07_55.tar.gz](https://github.com/DogDayAndroid/Android-Kernel-Builder/files/11729210/KernelSU_bugreport_2023-06-13_07_55.tar.gz)
> ![Sevenstar_20230613_081532](https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/72426083/5a22cbaa-6d6d-4d51-918d-261358ebd25f)
> 

考虑增加的其他编译选项中对应的 `kernel/configs/cruel`下的`conf`文件中是否开启了对应选项没有删除，或者关闭其他编译选项重试。

**Comment by easterNday** [comment]
> > 请参考我的[复刻提交](https://github.com/easterNday/samsung-exynos9820/commit/54edd3883aade78d806a48e50b61c0560499f540)。
> > 
> > 在这段代码里，我实现了简单的KIernelSU的同步，同时我移除了`Magisk`，如果您需要同时开启`Magisk`，请恢复[对应行](https://github.com/easterNday/samsung-exynos9820/commit/54edd3883aade78d806a48e50b61c0560499f540#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L60)。
> > 
> > 这只是一个简单实现，原项目代码中存在很多其他功能，因此请确保不会冲突。
> 
> 另外，是不是还需要加入AnyKernel3-master的支持才行？

原项目中已经启用了 `MagiskBoot` 等工具来生成 `boot.img`，因此可以不需要 `AnyKernel3` 支持。

如果您一定有需求使用 `AnyKernel3`，请参考本项目的实现。

**Comment by Star-Seven** [comment]
> > > 请参考我的[复刻提交](https://github.com/easterNday/samsung-exynos9820/commit/54edd3883aade78d806a48e50b61c0560499f540)。
> > > 在这段代码里，我实现了简单的KIernelSU的同步，同时我移除了`Magisk`，如果您需要同时开启`Magisk`，请恢复[对应行](https://github.com/easterNday/samsung-exynos9820/commit/54edd3883aade78d806a48e50b61c0560499f540#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L60)。
> > > 这只是一个简单实现，原项目代码中存在很多其他功能，因此请确保不会冲突。
> > 
> > 
> > 另外，是不是还需要加入AnyKernel3-master的支持才行？
> 
> 原项目中已经启用了 `MagiskBoot` 等工具来生成 `boot.img`，因此可以不需要 `AnyKernel3` 支持。
> 
> 如果您一定有需求使用 `AnyKernel3`，请参考本项目的实现。

晓得 了，可能还是需要修改其他参数才能解决overlayfs的问题。。

**Comment by Star-Seven** [comment]
> > 原内核（magisk版）的kernelsu是不可用的。编译后的kernelsu内核magisk也还能正常用（可能这就是问题？）尝试按kernelsu提交的issue  [tiann/KernelSU#263](https://github.com/tiann/KernelSU/issues/263)
> > 关闭了也还是不行，可能需要重新修改magisk配置以关闭magisk才行
> > [KernelSU_bugreport_2023-06-13_07_55.tar.gz](https://github.com/DogDayAndroid/Android-Kernel-Builder/files/11729210/KernelSU_bugreport_2023-06-13_07_55.tar.gz)
> > ![Sevenstar_20230613_081532](https://user-images.githubusercontent.com/72426083/245314801-5a22cbaa-6d6d-4d51-918d-261358ebd25f.jpg)
> 
> 考虑增加的其他编译选项中对应的 `kernel/configs/cruel`下的`conf`文件中是否开启了对应选项没有删除，或者关闭其他编译选项重试。

这次正常工作了，晚点我看看具体是哪个参数影响了

**Comment by Star-Seven** [comment]
昙花一现的正常。重启又挂了，（只有重刷才能正常）

**Comment by easterNday** [comment]
> 昙花一现的正常。重启又挂了，（只有重刷才能正常）

考虑设备是否是AB分区，如果为AB分区则可能是未使用的分区恢复到在使用中的分区内了，此时应该同时刷写AB两个分区。

**Comment by Star-Seven** [comment]
> > 昙花一现的正常。重启又挂了，（只有重刷才能正常）
> 
> 晚上我也遇到了这个问题，考虑刷入的时候清除 `Dalvik Cache` 和 `Cache`，好像可以解决。

暂时没辙，现在怎么刷都提示不支持overlayfs。真就是昙花一现。。。

**Comment by easterNday** [comment]
依旧建议注释此处的[额外编译选项](https://github.com/Star-Seven/samsung-exynos9820/blob/cruel-HVJ5-v5.3/.github/workflows/main.yml#L60-L69)后仅支持KernelSU功能进行编译，如果编译后可以正常使用 `KernelSU` 则考虑其他 `.conf` 问题。
正常使用，考虑除了增加的 `额外编译选项` 之外的内核源码内部相关的原因。
这样做确保了其他增加的额外编译选项不会干扰 `KernelSU` 的编译参数，如果这样做也不能

**Comment by Star-Seven** [comment]
> 依旧建议注释此处的[额外编译选项](https://github.com/Star-Seven/samsung-exynos9820/blob/cruel-HVJ5-v5.3/.github/workflows/main.yml#L60-L69)后仅支持KernelSU功能进行编译，如果编译后可以正常使用 `KernelSU` 则考虑其他 `.conf` 问题。 正常使用，考虑除了增加的 `额外编译选项` 之外的内核源码内部相关的原因。 这样做确保了其他增加的额外编译选项不会干扰 `KernelSU` 的编译参数，如果这样做也不能

。。可以再试试。自从上次正常一次后，重刷也同一个内核也不正常了。现在就卡在内核不支持overlayfs这个点上
