### ISSUE TITLE
GitHub releases upload fails 

### ISSUE THREAD

**Issue by sanjeevstunner** [DogDayAndroid/Android-Kernel-Builder#12]

**Comment by easterNday** [comment]
You need to open some permissions about workflow in actions in your settings.
This might be what you need: [link](https://github.com/softprops/action-gh-release/issues/236)

**Comment by easterNday** [comment]
Many people have asked this question, I think I will add it to my description later, thanks for asking.

**Comment by sanjeevstunner** [comment]
> Many people have asked this question, I think I will add it to readme later, thanks for asking.

Much appreciated, it actually worked after giving write permissions 👍 mentioning it in the readme will help a lot
