### ISSUE TITLE
add kernel vendor source support

### ISSUE THREAD

**Issue by dabao1955** [DogDayAndroid/Android-Kernel-Builder#15]
rt.
某些厂家(例如oppo)会把内核源码分成两个部分:
https://github.com/oppo-source/android_kernel_4.14_oppo_mt6893
https://github.com/oppo-source/android_kernel_modules_oppo_mt6893
只有一个内核源码会无法编译。

**Comment by easterNday** [comment]
请问如何将这两个源码合并到一起，摆放顺序有要求吗，还是放到同一个目录下就可以了。
暂时可以用自己创建一个仓库同步的办法解决这个问题。

**Comment by dabao1955** [comment]
> 请问如何将这两个源码合并到一起，摆放顺序有要求吗，还是放到同一个目录下就可以了。
> 暂时可以用自己创建一个仓库同步的办法解决这个问题。

内核内核源码仓库的软连接不一样，这个我也没有什么太好的方法。
