### ISSUE TITLE
Errors when building kernel

### ISSUE THREAD

**Issue by wolverine998** [DogDayAndroid/Android-Kernel-Builder#19]
On some kernels, there would be an error, stating **make /bin/sh: Argument list too long**. It works on some, on others it fails.

**Comment by easterNday** [comment]
Maybe should use `bash` but not `sh`, i'll change the code to use bash to compile.
Can u give me your `repos.json`, in that case i can test whether it is caused by `sh`.

**Comment by easterNday** [comment]
Consider whether it is a kernel configuration problem. There may be some `.mk`  files that have been included many times, causing the length of the environment variable `PATH`  to be too long.
