### ISSUE TITLE
OnePlus 10 Pro编译失败

### ISSUE THREAD

**Issue by likeman66** [DogDayAndroid/Android-Kernel-Builder#2]
仓库地址：https://github.com/likeman66/Android-Kernel-Builder
OnePlus内核地址：https://github.com/OnePlusOSS/android_kernel_msm-5.10_oneplus_sm8450
报错内容：<img width="1728" alt="image" src="https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/59259075/d95317ba-c9fc-47b2-898f-f0a7db978e7f">

**Comment by easterNday** [comment]
错误在 `Make defconfig` 这一步，考虑编译工具链问题，感觉 `clang` 版本应该设置为 `13`.

**Comment by easterNday** [comment]
查看了源代码仓库，似乎开源出来的内核缺少文件，请考虑更换为别的内核仓库。

详细缺少文件可以参考[Seriously OnePlus ? When do we get src we can build?](https://github.com/OnePlusOSS/android_kernel_msm-5.10_oneplus_sm8450/issues/4)，其中提到了这个问题。

**Comment by likeman66** [comment]
> 查看了源代码仓库，似乎开源出来的内核缺少文件，请考虑更换为别的内核仓库。
> 
> 详细缺少文件可以参考[Seriously OnePlus ? When do we get src we can build?](https://github.com/OnePlusOSS/android_kernel_msm-5.10_oneplus_sm8450/issues/4)，其中提到了这个问题。

好的，十分感谢！

**Comment by likeman66** [comment]
> 查看了源代码仓库，似乎开源出来的内核缺少文件，请考虑更换为别的内核仓库。
> 
> 详细缺少文件可以参考[Seriously OnePlus ? When do we get src we can build?](https://github.com/OnePlusOSS/android_kernel_msm-5.10_oneplus_sm8450/issues/4)，其中提到了这个问题。
> 
> 或许你可以尝试一下这个仓库[tangalbert919/android_kernel_oneplus_sm8450](https://github.com/tangalbert919/android_kernel_oneplus_sm8450)

试了下这个您提供的仓库，最后buidl阶段还是会报错，这是报错log文件，麻烦您有时间看看
[logs_9.zip](https://github.com/DogDayAndroid/Android-Kernel-Builder/files/11712094/logs_9.zip)

**Comment by easterNday** [comment]
请先尝试更换编译工具链，具体可以参考[[内核向] 交叉编译器的选择](https://web.archive.org/web/20230130041202/https://www.akr-developers.com/d/129).

**Comment by likeman66** [comment]
> 请先尝试更换编译工具链，具体可以参考[[内核向] 交叉编译器的选择](https://web.archive.org/web/20230130041202/https://www.akr-developers.com/d/129)。通过修改 `repos.json` 中对应的 `toolchains` 字段可以实现交叉编译器的更换，我查看其他的 `fork` 后发现一部分小米手机机型使用我参数配置里的 `clang` 版本设置为 `12` 或者 `13` 后成功编译。您可以尝试一下。

尝试换成了12或者13，也都编译失败了

**Comment by easterNday** [comment]
我这边报错内容如下：

```
>>> referenced by oplus_sensor_devinfo.c:1286 (/home/runner/work/Thyme-Kernel-Builder/Thyme-Kernel-Builder/OnePlus_Google_20/drivers/soc/oplus/sensor/oplus_sensor_devinfo.c:1286)
>>>               soc/oplus/sensor/oplus_sensor_devinfo.o:(oplus_devinfo_probe) in archive drivers/built-in.a

ld.lld: error: undefined symbol: qcom_smem_get
>>> referenced by oplus_sensor_devinfo.c:1295 (/home/runner/work/Thyme-Kernel-Builder/Thyme-Kernel-Builder/OnePlus_Google_20/drivers/soc/oplus/sensor/oplus_sensor_devinfo.c:1295)
>>>               soc/oplus/sensor/oplus_sensor_devinfo.o:(oplus_devinfo_probe) in archive drivers/built-in.a

ld.lld: error: undefined symbol: get_project
>>> referenced by oplus_sensor_devinfo.c:150 (/home/runner/work/Thyme-Kernel-Builder/Thyme-Kernel-Builder/OnePlus_Google_20/drivers/soc/oplus/sensor/oplus_sensor_devinfo.c:150)
>>>               soc/oplus/sensor/oplus_sensor_devinfo.o:(oplus_devinfo_probe) in archive drivers/built-in.a
```

报错信息可以参考[ld.lld error undefined symbol main](https://juejin.cn/s/ld.lld%20error%20undefined%20symbol%20main)，**可能**是内核源码的问题。请尝试修改内核源码实现修复。

**Comment by easterNday** [comment]
刚才浏览了一下 `XDA` 论坛，论坛中也没有发现有其他开发者发布的内核源码，因此可能暂时除了官方公布的内核源码之外，暂时没有其他内核源码可用。而官方源码通常是残缺的，因此如果想要编译还需要自己进行安卓内核源码的修改和测试。

很抱歉，在内核源码修改部分我暂时无法给予任何帮助，因为我也在学习这方面的内容。

不知道还有其他问题吗，没有的话本 `issue` 将于不久后关闭。
