### ISSUE TITLE
编译后的文件如何使用

### ISSUE THREAD

**Issue by sojava-code** [DogDayAndroid/Android-Kernel-Builder#20]
刷入时报错，image is not a boot image
请问，如果打包成boot.img，可否给出详细的教程，谢谢~

**Comment by easterNday** [comment]
对于一些**A/B分区或其他新型分区**的机型来说，直接刷入编译后的文件是无法成功的，因为并不是完整的`boot.img`。
如果你需要将其打包为`boot.img`的话，您可能需要机器原本的`boot.img`文件并使用`magiskboot`等工具将编译产物替换到原来的`boot.img`文件中后再刷入。
本项目已经提供了`AnyKernel3`的刷机包，开启对应选项选项之后可以使用`TWRP`进行刷入，这样更方便。

**Comment by sojava-code** [comment]
编译后的文件应该是什么格式？使用Kernel Flasher输入包含Image.gz的压缩包时报错，并不能完成刷入。

**Comment by sojava-code** [comment]
似乎需要Image.gz-dtb

**Comment by easterNday** [comment]
`Image.gz-dtb` 并不会在每个内核编译文件中都存在，如果编译生成了 `Image.gz-dtb` 文件，那么你可以在类似于 [我的编译 Actions](https://github.com/easterNday/Thyme-Kernel-Builder/actions/runs/6098314023) 的 **Artifacts** 部分找到对应的文件。

我之前使用 `Kernel Flasher` 也没有刷入成功过，似乎要使用魔改过后的才能刷入（虽然我也没成功过），如果有可能的话尽量还是使用 `TWRP` 来进行输入，刷入的包类似于 [我的发布页面中的 Zip 文件](https://github.com/easterNday/Thyme-Kernel-Builder/releases)。
