### ISSUE TITLE
Unsupported NR_CPUS for lb tracepoint

### ISSUE THREAD

**Issue by GunaisHere** [DogDayAndroid/Android-Kernel-Builder#22]
[https://prnt.sc/gZW5B9DkYk8g](url)

**Comment by easterNday** [comment]
Please consider checking the kernel version and configuration.

See [Linux kernel compile error Unsupported NR_CPUS for lb tracepoint](https://stackoverflow.com/questions/51576617/linux-kernel-compile-error-unsupported-nr-cpus-for-lb-tracepoint) also.
