### ISSUE TITLE
wget in "Get Toolchain"

### ISSUE THREAD

**Issue by Lu5ck** [DogDayAndroid/Android-Kernel-Builder#24]
The wget in "Get Toolchain" is problematic. If the download file shares the same filename as others. For examples

1. https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android12L-release.tar.gz
2. https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android12L-release.tar.gz

The wget will not write the file if it already exist.

**Comment by easterNday** [comment]
Done.
