### ISSUE TITLE
Redmi Note10 Pro(Chopin)构建失败

### ISSUE THREAD

**Issue by 1030Panda** [DogDayAndroid/Android-Kernel-Builder#3]
仓库地址：https://github.com/1030Panda/Android-Kernel-Builder
内核地址：https://github.com/Yuyuko1024/kernel_xiaomi_chopin
![image](https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/113248487/3a7e3949-decc-419d-a1d2-a8f0db9e575e)

**Comment by easterNday** [comment]
请尝试更换编译工具链，或自行修复错误。

**Comment by easterNday** [comment]
通过修改 `repos.json` 中对应的 `toolchains` 字段可以实现交叉编译器的更换，我查看其他的 `fork` 后发现一部分小米手机机型使用我参数配置里的 `clang` 版本设置为 `12` 或者 `13` 后成功编译。您可以尝试一下。

**Comment by 1030Panda** [comment]
好的，我尝试一下

**Comment by 1030Panda** [comment]
尝试了一下，还是报错

**Comment by easterNday** [comment]
又查看了一下，这个内核源码不能直接编译。

详细见[YuyukoAOSPMod/kernel_xiaomi_chopin](https://github.com/YuyukoAOSPMod/kernel_xiaomi_chopin),仓库作者为同一人,且该版本内核更新，在`README.md`中作者做了如下说明：

```
!!!!!WARNING!!!!!
==============================
THIS KERNEL'S ORIGINAL BRANCH IS chopin-r-oss , CANNOT DIRECTLY BUILD FOR AOSP 12.1 !!!!
THIS CODE IS ONLY USE FOR GENERATE KERNEL HEADER
```

因此实际上他的源码并不可编译，而仅仅是用来生成内核头部信息的。

**Comment by 1030Panda** [comment]
好的，我尝试更换其他内核源试试，感谢

**Comment by easterNday** [comment]
已经帮你确定了一个可以编译的版本[AOSP-13-Mediatek/kernel_xiaomi_chopin](https://github.com/AOSP-13-Mediatek/kernel_xiaomi_chopin)，可以查看[我的构建](https://github.com/easterNday/Thyme-Kernel-Builder/actions/runs/5233937572/jobs/9449738498)。
