### ISSUE TITLE
Help: Getting error when I compile using Proton clang

### ISSUE THREAD

**Issue by akzzy** [DogDayAndroid/Android-Kernel-Builder#30]
/home/runner/work/Android-Kernel-Builder/Android-Kernel-Builder/proton-clang/bin/as: unrecognized option '-EL'
clang-13: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/home/runner/work/Android-Kernel-Builder/Android-Kernel-Builder/Pixebuild_Bluecross/arch/arm64/kernel/vdso32/Makefile:150: arch/arm64/kernel/vdso32/sigreturn.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/runner/work/Android-Kernel-Builder/Android-Kernel-Builder/proton-clang/bin/as: unrecognized option '-EL'
clang-13: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/home/runner/work/Android-Kernel-Builder/Android-Kernel-Builder/Pixebuild_Bluecross/arch/arm64/kernel/vdso32/Makefile:148: arch/arm64/kernel/vdso32/vgettimeofday.o] Error 1
make[1]: *** [arch/arm64/Makefile:267: vdso_prepare] Error 2
make[1]: Leaving directory '/home/runner/work/Android-Kernel-Builder/Android-Kernel-Builder/out'
make: *** [Makefile:152: sub-make] Error 2
Error: Process completed with exit code 2.

My device repo : https://github.com/akzzy/Android-Kernel-Builder/blob/main/repos/repos.b1c1.json

**Comment by easterNday** [comment]
In fact, the compilers used are different for different kernels. 
`Proton-clang` is just a more general compiler, but sometimes it is not so handy for some high-version/low-version kernels. 
Therefore you should try changing to another compiler.

For how to choose a cross compiler, you can refer to [[内核向] 交叉编译器的选择](https://web.archive.org/web/20230130041202/https://www.akr-developers.com/d/129).
