### ISSUE TITLE
k30s构建失败

### ISSUE THREAD

**Issue by a592345029** [DogDayAndroid/Android-Kernel-Builder#4]
请教下怎么回事
![Screenshot_2023-06-11-14-40-14-419_com qihoo contents](https://github.com/DogDayAndroid/Android-Kernel-Builder/assets/59142802/76383088-143c-4cee-bc71-cee656123bae)
仓库地址https://github.com/a592345029/Android-Kernel-Builder/
内核地址https://github.com/Rohail33/Realking_kernel_sm8250

**Comment by easterNday** [comment]
请先尝试修改如下部分：

```
{
  "repo": "https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone/",
  "branch": "11",
  "name": "clang"
}
```

将其中的 `11` 修改为 `12` 或者 `13`，截图中的问题是由于 `clang` 不支持的编译参数导致的，因此可以确定是 `clang` 版本问题。

**Comment by easterNday** [comment]
看到您这边编译已经成功了，不知道是否还有其他问题，如果没有的话稍后会关闭本 `issue`。
